Userstory2
kisa5/capstone-project pull request #6
Opened 2023-01-25 09:18 UTC by kisa5

2023-01-25 09:33 UTC, F-Kirchhoff requested changes
Great work! have a look at the comments. Next round it should be ready to go.

2023-01-25 09:33 UTC, F-Kirchhoff commented on components/ProjectCard.js
>      <>
You don't need these fragments. Please use them only if you want to return two or more elements "side by side" and not wrapped in a container element.

2023-01-25 09:33 UTC, F-Kirchhoff commented on lib/db.js
> +];
Nice data structure!

2023-01-25 09:33 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +  const project = projects[projectIndex];
you can combine those two lines:
```
const project = projects.find(project => project.slug === slug)
```

2023-01-25 09:33 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +    return null;
In the future you can redirect here with the router to your 404 page.

2023-01-25 09:33 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +      </button>
Please don't use a button for a link component.

2023-01-25 09:33 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +      </button>
You can style the Link though that it looks like a button.

2023-01-25 09:33 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +          <li key={task}>{task}</li>
The task might not be unique. You can add an id to your tasks though since they are already objects!

2023-01-25 16:48 UTC, kisa5 commented
Thank you Felix for your Advice! Did some changes.. 🙂

2023-01-26 10:13 UTC, merged

2023-01-26 10:16 UTC, F-Kirchhoff requested changes
Looks much better now. Please account the css issues, then your are ready to go!

2023-01-26 10:16 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +    return <p>404 page</p>;
okay, that is good for now, consider creating a dedicated page at some later point in time

2023-01-26 10:16 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +  left: 15px;
top and left are ignored in static positioning. So you can remove it.

2023-01-26 10:16 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +  font-size: 17px;
You may want to use rem here for accessibility reasons.

2023-01-26 10:16 UTC, F-Kirchhoff commented on pages/project/[slug].js
> +  font-size: 15;
you are missing the units here